import { test, expect } from '@playwright/test';

test('test admin create service', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Sign-In' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('admin_playwright@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Sign In as User' }).click();
  await page.getByRole('link', { name: 'Admin Tools' }).click();
  await page.getByRole('link', { name: 'Manage Services Create and' }).click();
  await page.getByRole('button', { name: 'Add New Service' }).click();
  await page.getByRole('textbox', { name: 'Service Name *' }).click();
  await page.getByRole('textbox', { name: 'Service Name *' }).fill('Service_temp');
  await page.getByRole('textbox', { name: 'Rate *' }).click();
  await page.getByRole('textbox', { name: 'Rate *' }).fill('10');
  await page.getByRole('checkbox', { name: 'Billing Type:One Time' }).check();
  await page.getByRole('textbox', { name: 'Description *' }).click();
  await page.getByRole('textbox', { name: 'Description *' }).fill('test');
  await page.getByRole('button', { name: 'Create Service' }).click();
  await expect(page.getByText('Service created successfully')).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Service_temp' })).toBeVisible();
  await expect(page.getByRole('row', { name: 'Service_temp test $10.00' }).getByRole('button').nth(1)).toBeVisible();
  await page.getByRole('button', { name: 'Playwright Admin' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Yes, Sign Out' }).click();
});


test('test car provider create car with service name: Service_temp', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Sign-In' }).click();
  await page.getByRole('button', { name: 'Car Provider' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('playwright@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Sign In as Car Provider' }).click();
  await page.getByRole('link', { name: 'Provider Tools' }).click();
  await page.getByRole('link', { name: 'Manage Cars Add, update, or' }).click();
  await page.getByRole('button', { name: 'Add New Car' }).click();
  await page.getByRole('textbox', { name: 'License Plate *' }).click();
  await page.getByRole('textbox', { name: 'License Plate *' }).fill('CarWithServiceTemp');
  await page.getByRole('textbox', { name: 'Brand *' }).click();
  await page.getByRole('textbox', { name: 'Brand *' }).fill('CU');
  await page.getByRole('textbox', { name: 'Model *' }).click();
  await page.getByRole('textbox', { name: 'Model *' }).fill('CEDT');
  await page.getByLabel('Color *').selectOption('Other');
  await page.getByRole('spinbutton', { name: 'Daily Rate (USD) *' }).click();
  await page.getByRole('spinbutton', { name: 'Daily Rate (USD) *' }).fill('10');
  await page.locator('div').filter({ hasText: /^Service_tempDaily: \$10\.00test$/ }).first().click();
  await page.getByRole('button', { name: 'Add Car' }).click();
  await expect(page.getByRole('cell', { name: 'CarWithServiceTemp' })).toBeVisible();
  await page.getByRole('button', { name: 'Playwright Test' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Yes, Sign Out' }).click();
});

test('test rent create reservation with car CarWithServiceTemp with a service name: Service_temp', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Sign-In' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('playwright@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Sign In as User' }).click();
  await page.getByRole('link', { name: 'Catalog' }).click();
  await page.locator('[data-test-id="catalog"] div').filter({ hasText: '$10.00/daysedanCU CEDT2025 •' }).getByRole('button').nth(1).click();
  await page.locator('div').filter({ hasText: /^Pickup Date$/ }).getByRole('textbox').fill('2027-05-22');
  await page.locator('div').filter({ hasText: /^Return Date$/ }).getByRole('textbox').fill('2027-05-23');
  await page.locator('div').filter({ hasText: /^Click to add services$/ }).nth(2).click();
  await page.getByText('Service_temp').click();
  await page.getByRole('button', { name: 'Additional Services 1 $' }).click();
  await expect(page.getByText('Service_temptest$20.00$10.00/day ×')).toBeVisible();
  await page.getByRole('button', { name: 'Confirm & Pay $3.40 Deposit' }).click();
  await expect(page.getByRole('heading', { name: 'Booking Successful!' })).toBeVisible();
  await page.getByText('Close').click();
  await page.getByRole('row', { name: 'CU CEDT CarWithServiceTemp' }).getByRole('link').click();
  await expect(page.getByText('Service_temp(+$10/day)')).toBeVisible();
  await page.getByRole('button', { name: 'Playwright Man' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Yes, Sign Out' }).click();
});